import type { ParsedFile } from "../diff/types";
import {
  formatInlineCommentWithSuggestion,
  isValidSuggestion,
} from "../github/suggestion-formatter";

// システムプロンプト
export const REVIEW_SYSTEM_PROMPT = `あなたは経験豊富なシニアソフトウェアエンジニアで、コードレビューのエキスパートです。
あなたの役割は、Pull Requestの変更を分析し、建設的で実行可能なフィードバックを提供することです。

## レビュー原則

1. **建設的であること**: 批判ではなく改善提案を
2. **具体的であること**: 一般論ではなく具体的なコードを指摘
3. **優先度を明確に**: CRITICALは必ず修正、NITPICKは任意
4. **理由を説明**: なぜ問題なのか、なぜ提案が有効なのか

## 深刻度の定義

- **CRITICAL**: セキュリティ脆弱性、データ損失、本番障害につながる問題
- **IMPORTANT**: バグ、パフォーマンス問題、設計上の問題
- **INFO**: ベストプラクティス、可読性の改善
- **NITPICK**: スタイル、命名規則、軽微な改善

## 出力形式

日本語で回答してください。コードブロックは適切な言語タグを使用してください。`;

// レビュープロンプト生成
export function buildReviewPrompt(params: {
  prTitle: string;
  prBody: string;
  files: ParsedFile[];
  diffContent: string;
  ragContext?: string;
}): string {
  const { prTitle, prBody, files, diffContent, ragContext } = params;

  const fileList = files
    .map((f) => `- ${f.newPath} (${f.type}: +${f.additions}/-${f.deletions})`)
    .join("\n");

  let prompt = `## Pull Request情報

**タイトル**: ${prTitle}

**説明**:
${prBody || "(説明なし)"}

## 変更ファイル一覧

${fileList}

## Diff内容

\`\`\`diff
${diffContent}
\`\`\`
`;

  if (ragContext) {
    prompt += `
## 関連コードコンテキスト（RAG）

以下は変更に関連する既存コードの抜粋です。レビュー時の参考にしてください。

${ragContext}
`;
  }

  prompt += `
## タスク

上記のPull Requestをレビューしてください。以下を出力してください：

1. **summary**: 変更内容の総合的なサマリー（何を変更したか、なぜ変更したか）
2. **walkthrough**: 各ファイルの変更概要
3. **comments**: 具体的なインラインコメント（問題点や改善提案）
4. **diagram**: （必要な場合のみ）アーキテクチャの変更を示すMermaidダイアグラム

コメントには必ず正確な行番号を指定してください。行番号はDiff内の新しいファイルの行番号を使用してください。`;

  return prompt;
}

// PRサマリーコメント生成
export function buildSummaryComment(params: {
  summary: string;
  walkthrough: Array<{ path: string; summary: string; changeType: string }>;
  diagram?: string | null;
  commentsCount: number;
  criticalCount: number;
  importantCount: number;
}): string {
  const {
    summary,
    walkthrough,
    diagram,
    commentsCount,
    criticalCount,
    importantCount,
  } = params;

  let comment = `## 🐴 CodeHorse Review Summary

${summary}

### 📁 変更ファイル

| ファイル | 変更タイプ | 概要 |
|----------|------------|------|
`;

  for (const file of walkthrough) {
    const typeEmoji = {
      add: "🆕",
      modify: "📝",
      delete: "🗑️",
      rename: "📛",
    }[file.changeType] || "📄";
    comment += `| \`${file.path}\` | ${typeEmoji} ${file.changeType} | ${file.summary} |\n`;
  }

  if (diagram) {
    comment += `
### 📊 アーキテクチャ図

\`\`\`mermaid
${diagram}
\`\`\`
`;
  }

  comment += `
### 📈 レビュー統計

- 💬 コメント数: ${commentsCount}
`;

  if (criticalCount > 0) {
    comment += `- 🔴 CRITICAL: ${criticalCount}\n`;
  }
  if (importantCount > 0) {
    comment += `- 🟠 IMPORTANT: ${importantCount}\n`;
  }

  comment += `
---
*🐴 Generated by [CodeHorse](https://github.com/codehorse)*`;

  return comment;
}

// インラインコメントのフォーマット
// GitHubネイティブのsuggestion block形式を使用
export function formatInlineComment(params: {
  body: string;
  severity: string;
  suggestion?: string;
}): string {
  const { body, severity, suggestion } = params;

  // 有効なsuggestionがある場合のみsuggestion blockを使用
  const validSuggestion = isValidSuggestion(suggestion) ? suggestion : undefined;

  return formatInlineCommentWithSuggestion({
    body,
    severity,
    suggestion: validSuggestion,
  });
}
